/*
Copyright 2026 keiailab.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by D.9.1 ShardSplitJob CRD addition (2026-05-19).
// Equivalent to controller-gen output — `make manifests` 가 향후 본 파일 일소 후
// zz_generated.deepcopy.go 에 통합 예정.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardSplitJob) DeepCopyInto(out *ShardSplitJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardSplitJob.
func (in *ShardSplitJob) DeepCopy() *ShardSplitJob {
	if in == nil {
		return nil
	}
	out := new(ShardSplitJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardSplitJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardSplitJobList) DeepCopyInto(out *ShardSplitJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		inItems, outItems := &in.Items, &out.Items
		*outItems = make([]ShardSplitJob, len(*inItems))
		for i := range *inItems {
			(*inItems)[i].DeepCopyInto(&(*outItems)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardSplitJobList.
func (in *ShardSplitJobList) DeepCopy() *ShardSplitJobList {
	if in == nil {
		return nil
	}
	out := new(ShardSplitJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardSplitJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardSplitJobSpec) DeepCopyInto(out *ShardSplitJobSpec) {
	*out = *in
	if in.Sources != nil {
		inS, outS := &in.Sources, &out.Sources
		*outS = make([]string, len(*inS))
		copy(*outS, *inS)
	}
	if in.Targets != nil {
		inT, outT := &in.Targets, &out.Targets
		*outT = make([]ShardSplitTarget, len(*inT))
		for i := range *inT {
			(*inT)[i].DeepCopyInto(&(*outT)[i])
		}
	}
	out.CutoverWindow = in.CutoverWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardSplitJobSpec.
func (in *ShardSplitJobSpec) DeepCopy() *ShardSplitJobSpec {
	if in == nil {
		return nil
	}
	out := new(ShardSplitJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardSplitTarget) DeepCopyInto(out *ShardSplitTarget) {
	*out = *in
	if in.Ranges != nil {
		inR, outR := &in.Ranges, &out.Ranges
		*outR = make([]ShardRangeEntry, len(*inR))
		copy(*outR, *inR)
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(ShardSplitPlacement)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardSplitTarget.
func (in *ShardSplitTarget) DeepCopy() *ShardSplitTarget {
	if in == nil {
		return nil
	}
	out := new(ShardSplitTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardSplitPlacement) DeepCopyInto(out *ShardSplitPlacement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardSplitPlacement.
func (in *ShardSplitPlacement) DeepCopy() *ShardSplitPlacement {
	if in == nil {
		return nil
	}
	out := new(ShardSplitPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardSplitJobStatus) DeepCopyInto(out *ShardSplitJobStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.CutoverStartedAt != nil {
		in, out := &in.CutoverStartedAt, &out.CutoverStartedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		inC, outC := &in.Conditions, &out.Conditions
		*outC = make([]metav1.Condition, len(*inC))
		for i := range *inC {
			(*inC)[i].DeepCopyInto(&(*outC)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardSplitJobStatus.
func (in *ShardSplitJobStatus) DeepCopy() *ShardSplitJobStatus {
	if in == nil {
		return nil
	}
	out := new(ShardSplitJobStatus)
	in.DeepCopyInto(out)
	return out
}
