apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bases/postgres.keiailab.io_backupjobs.yaml
- bases/postgres.keiailab.io_clusterimagecatalogs.yaml
- bases/postgres.keiailab.io_imagecatalogs.yaml
- bases/postgres.keiailab.io_poolers.yaml
- bases/postgres.keiailab.io_postgresdatabases.yaml
- bases/postgres.keiailab.io_postgresclusters.yaml
- bases/postgres.keiailab.io_postgresusers.yaml
- bases/postgres.keiailab.io_scheduledbackups.yaml
